### ISSUE TITLE
Unexpected Behavior when overriding default workspace and source

### ISSUE THREAD

**Issue by annamarieweber** [monosidev/monosi#48]
## Description

Attempting to override the default workspace and source in the monosi_project.yml is not successful. When monosi profile is run the overides are removed from the monosi_project.yml file and the default workspace an source are used.

## Expected behavior

When monosi profile is run on a project with overrides for workspace and source the specified workspace and source should be used. The monosi_project.yml file should still have the specified workspace and source in it after running monosi profile

_Please provide clear and concise description of what you expected to happen._

## Steps to reproduce

1.  Add an additional workspace to /.monosi/workspaces.yml as shown below
```yml
default:
    sources:
        default:
            type: snowflake
            user: <snowflake_username>
            password: <snowflake_password>
            account: <snowflake_acct>
            warehouse: COMPUTE_WH
            database: SNOWFLAKE_SAMPLE_DATA
testworkspace:
  sources:
        testsource:
            type: postgres
            user: <postgres_username>
            host: <postgres_host>
            port: 5432
            database: <postgres_database_name>
            password: <postgres_password>
```
2. Navigate to your monosi project directory and open monosi_project.yml
3. Add override configurations to the file as shown below
```yml
name: monosi-repo
version: 0.0.3
monitor-paths:
- ./monitors
- ./bootstrapped-monitors
workspace: testworkspace
source: testsource
```

4. run `monosi profile`
5. when it completes navigate to the bootstrapped-monitors directory and run ls you will see that the default snowflake data was used 
6. navigate back to the root directory and open the monosi-project.yml file and you will see the workspace and source overrides are no longer there

## Additional context

before running monosi profile
<img width="299" alt="Screen Shot 2022-02-04 at 7 31 21 PM" src="https://user-images.githubusercontent.com/65051716/152627347-6a735003-ae58-4227-9113-d71a900588d4.png">

after running monosi profile 
<img width="238" alt="Screen Shot 2022-02-04 at 7 31 40 PM" src="https://user-images.githubusercontent.com/65051716/152627357-f2a2d37a-12d3-4b0f-a0d0-c304c94ce35f.png">
